name: "scp-wa-backend"

concurrency:  
  group: ${{ github.event.client_payload.repo_name }}-${{ github.event.client_payload.branch || github.event.client_payload.sha }}
  cancel-in-progress: true

on:
  repository_dispatch:
    types: 
      - scp-wa-backend 

jobs:
  build:
    runs-on: ubuntu-18.04
    env:
      PAYLOAD: ${{ toJSON(github.event.client_payload) }}
      GIT_URL: ${{ github.event.client_payload.git_url }}
      BRANCH: ${{ github.event.client_payload.branch }}
      REPO: ${{ github.event.client_payload.repo_name }}
      GL_PAT: ${{ secrets.GL_PAT }}
    steps:
      - name: Checkout
        shell: bash
        env:
          GIT_DEPTH: ${{ github.event.client_payload.git_depth || 1 }}
        run: |
          git clone --depth $GIT_DEPTH --single-branch --branch $BRANCH https://oauth2:$GL_PAT@$GIT_URL .

      - name: Test
        run: ls -lah 
