name: "scp-wa-backend"

concurrency:  
  group: ${{ github.event.client_payload.repo_name }}-${{ github.event.client_payload.branch || github.event.client_payload.sha }}
  cancel-in-progress: true

on:
  repository_dispatch:
    types: 
      - scp-wa-backend 

jobs:
  build:
    defaults:
      run:
        working-directory: ${{ github.event.client_payload.repo_name }}
    env:
      PAYLOAD: ${{ toJSON(github.event.client_payload) }}
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        shell: bash
        env: 
          GIT_URL: ${{ github.event.client_payload.git_url }}
          BRANCH: ${{ github.event.client_payload.branch }}
        run: |
          git clone https://oauth2:${{ secrets.GL_PAT }}@$GIT_URL
          git checkout $BRANCH
      
      - name: Test
        run: ls -lah
