name: "test"

on: 
  - push

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      
      - name: Test 
        run: echo "test"
  
  docker:
    runs-on: ubuntu-18.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      
      - name: Test 
        run: exit 1

  notify:
    needs:
      - test
      - docker
    runs-on: ubuntu-18.04
    if: always()
    steps:
      - name: Pass
        env:
          CONTEXT: ${{ toJSON(needs) }}
        run: |
          echo "Test: ${{ needs.test.result }}"
          echo "Docker: ${{ needs.docker.result }}"
          
          echo -n '${{ toJSON(needs) }}' | jq
