name: "test"

on: 
  - push

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      
      - name: Test 
        run: echo "test"
  
  docker:
    runs-on: ubuntu-18.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      
      - name: Test 
        run: exit 1

  notify:
    runs-on: ubuntu-18.04
    if: failure()
    steps:
      - name: Pass
        run: echo "PASSED"
